### ISSUE TITLE
DOI lookup in URL requires encoding

### ISSUE THREAD

**Issue by rowanc1** [ourresearch/openalex-docs#1]
It took me a while to figure out how to look up based on a DOI:

Fails:
https://explore.openalex.org/works/doi:10.1016/j.cageo.2015.09.015

Works:
https://explore.openalex.org/works/doi:10.1016%2Fj.cageo.2015.09.015
https://explore.openalex.org/works/doi%3A10.1016%2Fj.cageo.2015.09.015
https://explore.openalex.org/works/https%3A%2F%2Fdoi.org%2F10.1016%2Fj.cageo.2015.09.015

Even a hint in the docs that `/` --> `%2F` could be useful!

Perhaps in your get single entity page:

After:
> ## namespace:id format
> This is the namespace of the identifier, followed by a colon, and then the ID itself. It works for all IDs that we support. examples:
> doi:10.123
> ror:456
> openalex:w4242
```
Note: The ID must be URI encoded, for example, the `/` in a DOI should be encoded as `%2F`. For example, in javascript you can use the `encodeURIComponent(myDOI)` function.
```

**Comment by hpiwowar** [comment]
Thanks for this suggestion Rowan!  Yes I think we hadn't thought much about documenting the doi in the Explore url -- the escaping isn't needed in the API format.  We'll think about how best to handle this.  Thanks for letting us know it was confusing!

**Comment by rowanc1** [comment]
Oh right, I suppose I wasn't trying this in the API. Assumed they were the same!
